// Language Miner Tier 3 Arcade — entitlement-gated study mini games.
(()=>{
'use strict';
const GAMES=[
 {id:'memory',icon:'🧠',name:'Memory Mine',tag:'Memorization game',description:'Reveal cards and remember six learning-language word pairs.',instruction:'Match every learning-language word with its known-language meaning.'},
 {id:'matching',icon:'🔗',name:'Crystal Match',tag:'Matching game',description:'Connect words to their meanings before the clock runs out.',instruction:'Select a learning word, then select its matching meaning.'},
 {id:'shooter',icon:'🚀',name:'Star Word Defender',tag:'Timed alignment game',description:'Move the arrow beneath the correct falling word to score.',instruction:'Align the arrow with the matching word before it reaches the target line.'}
];
const PAIRS_FALLBACK=[['人','person'],['日','day / sun'],['月','moon / month'],['火','fire'],['水','water'],['木','tree'],['山','mountain'],['川','river'],['口','mouth'],['目','eye'],['手','hand'],['友達','friend']];
const $=selector=>document.querySelector(selector),escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const shuffle=values=>{const copy=[...values];for(let index=copy.length-1;index>0;index--){const swap=Math.floor(Math.random()*(index+1));[copy[index],copy[swap]]=[copy[swap],copy[index]];}return copy;};
const tier=()=>Math.max(0,Number(window.japaneseMinerSupporterTier?.()||0));
function ensure(){state.v6=state.v6&&typeof state.v6==='object'?state.v6:{};state.v6.arcadeOwned=Array.isArray(state.v6.arcadeOwned)?[...new Set(state.v6.arcadeOwned.map(String).filter(id=>GAMES.some(game=>game.id===id)))]:[];state.v6.arcadeBest=state.v6.arcadeBest&&typeof state.v6.arcadeBest==='object'&&!Array.isArray(state.v6.arcadeBest)?state.v6.arcadeBest:{};if(typeof state.v6.arcadeBagExpanded!=='boolean')state.v6.arcadeBagExpanded=true;}
function owned(id){ensure();return state.v6.arcadeOwned.includes(String(id));}
function claim(id){ensure();if(tier()<3)return false;if(!GAMES.some(game=>game.id===id))return false;if(!owned(id)){state.v6.arcadeOwned.push(id);save();}return true;}
function gate(feature='Arcade mini games'){return window.japaneseMinerSupporterGate?.(3,feature)||'<p>Patreon Tier 3 is required.</p>';}
function shopMarkup(){ensure();if(tier()<3)return gate('Arcade mini games');return `<section class="arcade-collection-head"><span>PATREON TIER 3 · $5 PATREON COLLECTION</span><h3>🕹️ Study Arcade</h3><p>Claim each mini game once, then launch it anytime from the Shop or your Bag. No Nuggets are charged.</p></section><div class="arcade-library">${GAMES.map(game=>gameCard(game,'shop')).join('')}</div>`;}
function bagMarkup(){ensure();if(tier()<3)return `<section class="arcade-bag-gate"><h3>🕹️ Study Arcade</h3><p>Your Tier 3 mini games will appear here after you connect the $5 Patreon membership.</p>${gate('Arcade mini games')}</section>`;const claimed=GAMES.filter(game=>owned(game.id)),expanded=state.v6.arcadeBagExpanded!==false;return `<div class="owned-inventory-title arcade-bag-title"><span>Tier 3 game bag · $5 Patreon</span><h3>🕹️ Study Arcade</h3><p>${claimed.length?`${claimed.length} mini game${claimed.length===1?'':'s'} ready to play.`:'Claim mini games from the Shop, then they will appear here.'}</p><button class="arcade-bag-toggle" type="button" data-arcade-bag-toggle aria-expanded="${expanded}" aria-controls="arcadeBagLibrary" aria-label="${expanded?'Collapse':'Expand'} Study Arcade"><span aria-hidden="true">${expanded?'▲':'▼'}</span></button></div><div id="arcadeBagLibrary" class="arcade-library arcade-bag-library" ${expanded?'':'hidden'}>${(claimed.length?claimed:GAMES).map(game=>gameCard(game,claimed.length?'bag':'unclaimed')).join('')}</div>`;}
function gameCard(game,location){const has=owned(game.id),best=state.v6.arcadeBest[game.id],disabled=location==='unclaimed';return `<article class="arcade-game-card ${has?'owned':'claimable'} ${disabled?'unclaimed':''}"><div class="arcade-game-icon">${game.icon}</div><span>${escape(game.tag)}</span><h3>${escape(game.name)}</h3><p>${escape(game.description)}</p><small>${best?`Best: ${escape(bestLabel(game.id,best))}`:has?'Unlocked in your Bag':'Included with Tier 3 · $5 Patreon'}</small><button type="button" data-arcade-${has?'play':'claim'}="${game.id}" ${disabled?'disabled':''}>${has?'Play now':'Unlock mini game'}</button></article>`;}
function bind(container,refresh){container?.querySelectorAll('[data-arcade-claim]').forEach(button=>button.addEventListener('click',()=>{if(claim(button.dataset.arcadeClaim)){setMessage?.('Mini game unlocked and added to your Bag.','correct');refresh?.();}}));container?.querySelectorAll('[data-arcade-play]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.arcadePlay)));container?.querySelectorAll('[data-arcade-lesson-select]').forEach(select=>select.addEventListener('change',()=>{if(selectLesson(select.value))refresh?.();}));const bagToggle=container?.querySelector('[data-arcade-bag-toggle]');if(bagToggle)bagToggle.addEventListener('click',()=>{ensure();const expanded=bagToggle.getAttribute('aria-expanded')!=='true',library=container.querySelector('#arcadeBagLibrary'),arcadeName=window.LanguageMinerI18n?.translate?.('Study Arcade')||'Study Arcade';state.v6.arcadeBagExpanded=expanded;bagToggle.setAttribute('aria-expanded',String(expanded));bagToggle.setAttribute('aria-label',window.LanguageMinerI18n?.t?.(expanded?'collapse':'expand',{value:arcadeName})||`${expanded?'Collapse':'Expand'} Study Arcade`);bagToggle.querySelector('span').textContent=expanded?'▲':'▼';if(library)library.hidden=!expanded;container.classList.toggle('collapsed',!expanded);save();});}
function knownMeaning(learn,fallback,known){const data=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA||{};for(const group of ['vocabulary','grammar','sentences']){const item=(data[group]||[]).find(entry=>String(entry?.forms?.ja||'')===String(learn||''));if(item?.forms?.[known])return String(item.forms[known]);}return String(fallback||learn||'');}
function japaneseLesson(stage=typeof selectedStageIndex==='function'?selectedStageIndex():0,section='',lesson=-1){
 const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{},known=String(settings.known||'en');stage=Number(stage)||0;
 try{
  if(stage<=1){const families=kanaFamiliesForStage(stage),index=lesson>=0?Number(lesson):Number(state.kanaFamilyLevel?.[stage===1?'katakana':'hiragana']||0),family=families[index]||families[0],pairs=(family?.entries||[]).map(([character,romanization],itemIndex)=>({id:`ja-${stage}-kana-${index}-${itemIndex}`,learn:String(character),meaning:String(romanization)}));return {key:`ja:${stage}:kana:${index}`,learning:'ja',known,mine:stage,section:'alphabet',lesson:index,label:`${stages[stage]?.name||stages[stage]?.label||'Japanese'} · ${family?.name||`Lesson ${index+1}`}`,pairs};}
  section=section||currentJlptSection(stage);const level=lesson>=0?Number(lesson):currentJlptSectionLevel(stage,section),items=jlptSectionLevels(stage,section)[level]||[],spec=jlptSectionSpec(section),pairs=[];
  items.forEach((item,index)=>{const learn=String(item?.primary||item?.jp||''),fallback=item?.meaning||item?.secondary||item?.detail;if(learn&&fallback&&learn!==String(fallback))pairs.push({id:`ja-${stage}-${section}-${level}-${item?.masteryId||item?.key||index}`,learn,meaning:knownMeaning(learn,fallback,known)});});
  return {key:`ja:${stage}:${section}:${level}`,learning:'ja',known,mine:stage,section,lesson:level,label:`${stages[stage]?.label||stages[stage]?.name||'Japanese'} · ${spec?.name||section} · Lesson ${level+1}`,pairs};
 }catch{return null;}
}
function japaneseLessonOptions(){const options=[];try{for(let stage=0;stage<stages.length;stage++){if(!isStageUnlocked(stage))continue;if(stage<=1){kanaFamiliesForStage(stage).forEach((family,index)=>{if(kanaFamilyUnlocked(stage,index)&&family.entries.length)options.push({key:`ja:${stage}:kana:${index}`,label:`${stages[stage]?.name||stages[stage]?.label||'Japanese'} · ${family.name||`Lesson ${index+1}`}`});});continue;}for(const spec of JLPT_SECTION_SPECS){jlptSectionLevels(stage,spec.id).forEach((items,index)=>{if(items.length&&jlptSectionLevelUnlocked(stage,spec.id,index))options.push({key:`ja:${stage}:${spec.id}:${index}`,label:`${stages[stage]?.label||stages[stage]?.name||'Japanese'} · ${spec.name} · Lesson ${index+1}`});});}}}catch{}return options;}
function currentLesson(){const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{},learning=String(settings.learning||'ja'),known=String(settings.known||'en');if(learning!=='ja'){const selected=window.LanguageMinerCourseLesson?.current?.();if(selected?.pairs?.length)return selected;}else{const selected=japaneseLesson();if(selected?.pairs?.length)return selected;}const source=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA?.vocabulary||[],pairs=[];for(const item of source){const learn=item?.forms?.[learning],meaning=item?.forms?.[known];if(learn&&meaning&&learn!==meaning&&!pairs.some(pair=>pair.learn===learn))pairs.push({id:`fallback-course-${item.id}`,learn:String(learn),meaning:String(meaning)});if(pairs.length>=25)break;}if(!pairs.length)PAIRS_FALLBACK.forEach(([learn,meaning],index)=>pairs.push({id:`fallback-${index}`,learn,meaning}));return {key:'fallback',learning,known,mine:0,section:'vocabulary',lesson:0,label:'Current lesson',pairs};}
function lessonOptions(){const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{};return String(settings.learning||'ja')==='ja'?japaneseLessonOptions():(window.LanguageMinerCourseLesson?.options?.()||[]);}
function selectLesson(key){key=String(key||'');const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{};if(String(settings.learning||'ja')!=='ja')return window.LanguageMinerCourseLesson?.select?.(key)===true;const match=/^ja:(\d+):([a-z]+):(\d+)$/.exec(key);if(!match)return false;const stage=Number(match[1]),section=match[2],lesson=Number(match[3]);try{selectStage(stage,false);if(stage<=1)selectKanaFamily(stage,lesson);else selectJlptSectionLevel(stage,section,lesson);return currentLesson().key===key;}catch{return false;}}
function lessonSourceMarkup(source,{selectable=false}={}){const options=selectable?lessonOptions():[],control=selectable&&options.length?`<select data-arcade-lesson-select aria-label="Current lesson">${options.map(option=>`<option value="${escape(option.key)}" ${option.key===source.key?'selected':''}>${escape(option.label)}</option>`).join('')}</select>`:`<strong>${escape(source.label)}</strong>`;return `<div class="arcade-lesson-source"><span>Current lesson</span>${control}</div>`;}
function vocabularyPairs(count=12){const source=currentLesson(),pairs=shuffle(source.pairs).slice(0,Math.max(2,Math.min(Number(count)||12,source.pairs.length)));return {source,pairs};}
function bindGameLessonSelector(id){const select=$('[data-arcade-lesson-select]');if(select)select.onchange=()=>{if(selectLesson(select.value))start(id);};}
let session=null,timer=null,animation=null;
function shell(){if($('#arcadeOverlay'))return;document.body.insertAdjacentHTML('beforeend',`<div id="arcadeOverlay" class="arcade-overlay" aria-hidden="true"><section class="arcade-panel" role="dialog" aria-modal="true" aria-labelledby="arcadeTitle"><header><button id="arcadeBack" type="button">← Arcade</button><div><span>Tier 3 Study Arcade</span><h2 id="arcadeTitle">Mini game</h2></div><button id="arcadeClose" type="button" aria-label="Close mini game">×</button></header><main id="arcadeContent"></main></section></div>`);$('#arcadeClose').onclick=close;$('#arcadeBack').onclick=renderLibrary;$('#arcadeOverlay').onclick=event=>{if(event.target.id==='arcadeOverlay')close();};}
function open(id=''){ensure();if(tier()<3){window.openJapaneseMinerPatreon?.();return false;}if(id&&!owned(id)){window.openJapaneseMinerArcadeShop?.();return false;}closeOtherOverlays();shell();$('#arcadeOverlay').classList.add('open');$('#arcadeOverlay').setAttribute('aria-hidden','false');window.syncJapaneseMinerPageScroll?.();if(id)start(id);else renderLibrary();return true;}
function close(){stopRuntime();$('#arcadeOverlay')?.classList.remove('open');$('#arcadeOverlay')?.setAttribute('aria-hidden','true');window.syncJapaneseMinerPageScroll?.();}
function stopRuntime(){if(timer){clearInterval(timer);timer=null;}if(animation){cancelAnimationFrame(animation);animation=null;}session=null;}
function renderLibrary(){stopRuntime();$('#arcadeTitle').textContent='Study Arcade';$('#arcadeBack').hidden=true;const content=$('#arcadeContent'),source=currentLesson();content.innerHTML=`<section class="arcade-collection-head"><span>YOUR TIER 3 MINI GAMES</span><h3>Choose a game</h3><p>Each activity uses words from the selected learning language and meanings from the selected known language.</p>${lessonSourceMarkup(source,{selectable:true})}</section><div class="arcade-library">${GAMES.filter(game=>owned(game.id)).map(game=>gameCard(game,'bag')).join('')||'<p class="arcade-empty">Unlock a mini game from the Shop first.</p>'}</div>`;bind(content,renderLibrary);}
function start(id){if(tier()<3||!owned(id)){close();return false;}stopRuntime();const game=GAMES.find(item=>item.id===id);if(!game)return false;$('#arcadeTitle').textContent=game.name;$('#arcadeBack').hidden=false;if(id==='memory')startMemory();else if(id==='matching')startMatching();else startShooter();return true;}
function record(id,value){ensure();value=Number(value);if(!Number.isFinite(value))return;const old=Number(state.v6.arcadeBest[id]),hasOld=Number.isFinite(old);if(id==='memory'||id==='matching'){if(!hasOld||value<old)state.v6.arcadeBest[id]=value;}else if(!hasOld||value>old)state.v6.arcadeBest[id]=value;save();}
function bestLabel(id,value){return id==='memory'?`${value} moves`:id==='matching'?`${value}s`:`${value} points`;}
function finishView(id,title,detail,value,resultLabel=''){if(Number.isFinite(Number(value)))record(id,value);stopRuntime();const game=GAMES.find(item=>item.id===id),label=resultLabel||(Number.isFinite(Number(value))?bestLabel(id,value):'');$('#arcadeContent').innerHTML=`<section class="arcade-results"><span>${game.icon}</span><h3>${escape(title)}</h3><p>${escape(detail)}</p>${label?`<strong>${escape(label)}</strong>`:''}<div><button type="button" data-arcade-replay="${id}">Play again</button><button type="button" id="arcadeResultsLibrary">Choose another game</button></div></section>`;$('[data-arcade-replay]').onclick=()=>start(id);$('#arcadeResultsLibrary').onclick=renderLibrary;}
function startMemory(){const lesson=vocabularyPairs(6),pairs=lesson.pairs,cards=shuffle(pairs.flatMap(pair=>[{key:pair.id,type:'learn',text:pair.learn},{key:pair.id,type:'meaning',text:pair.meaning}]));session={id:'memory',source:lesson.source,pairs,cards,open:[],matched:new Set(),moves:0,locked:false};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>MEMORIZATION GAME</span><h3>Connect the word pairs</h3><p>Flip two cards. Match each learning word with its known-language meaning.</p></div><strong id="arcadeMemoryMoves">0 moves</strong></section>${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-memory-grid" data-lm-no-interface-translate>${cards.map((card,index)=>`<button type="button" data-memory-card="${index}" data-memory-key="${escape(card.key)}" aria-label="Hidden memory card"><span class="arcade-memory-cover">⛏️</span><b class="arcade-memory-word" hidden>${escape(card.text)}</b></button>`).join('')}</div>`;bindGameLessonSelector('memory');document.querySelectorAll('[data-memory-card]').forEach(button=>button.onclick=()=>flipMemory(Number(button.dataset.memoryCard)));}
function setMemoryCardVisible(index,visible){const button=$(`[data-memory-card="${index}"]`);if(!button)return;button.classList.toggle('revealed',visible);const cover=button.querySelector('.arcade-memory-cover'),word=button.querySelector('.arcade-memory-word');if(cover)cover.hidden=visible;if(word)word.hidden=!visible;}
function flipMemory(index){const s=session;if(s?.id!=='memory'||s.locked||s.matched.has(s.cards[index].key)||s.open.includes(index))return;const button=$(`[data-memory-card="${index}"]`);setMemoryCardVisible(index,true);button.setAttribute('aria-label',s.cards[index].text);s.open.push(index);if(s.open.length<2)return;s.moves++;$('#arcadeMemoryMoves').textContent=`${s.moves} moves`;const [a,b]=s.open;if(s.cards[a].key===s.cards[b].key&&s.cards[a].type!==s.cards[b].type){s.matched.add(s.cards[a].key);[a,b].forEach(value=>$(`[data-memory-card="${value}"]`).classList.add('matched'));s.open=[];if(s.matched.size===s.pairs.length)setTimeout(()=>finishView('memory','Memory Mine cleared!',`You matched all ${s.pairs.length} word pairs in ${s.moves} moves.`,s.moves),350);return;}s.locked=true;setTimeout(()=>{[a,b].forEach(value=>setMemoryCardVisible(value,false));s.open=[];s.locked=false;},700);}
function startMatching(){const lesson=vocabularyPairs(8),pairs=lesson.pairs;session={id:'matching',source:lesson.source,pairs,left:null,right:null,matched:new Set(),score:0,time:60};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>MATCHING GAME</span><h3>Connect the word pairs</h3><p>Choose one tile from each column. You have 60 seconds.</p></div><strong id="arcadeMatchTimer">60s</strong></section>${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-match-status" id="arcadeMatchStatus">Select a learning word.</div><div class="arcade-match-board" data-lm-no-interface-translate><div>${shuffle(pairs).map(pair=>`<button type="button" data-match-side="left" data-match-id="${pair.id}">${escape(pair.learn)}</button>`).join('')}</div><div>${shuffle(pairs).map(pair=>`<button type="button" data-match-side="right" data-match-id="${pair.id}">${escape(pair.meaning)}</button>`).join('')}</div></div>`;bindGameLessonSelector('matching');document.querySelectorAll('[data-match-side]').forEach(button=>button.onclick=()=>selectMatch(button));timer=setInterval(()=>{if(session?.id!=='matching')return;session.time--;$('#arcadeMatchTimer').textContent=`${session.time}s`;if(session.time<=0)finishView('matching','Time is up!',`You connected ${session.score} of ${session.pairs.length} pairs.`,null,`${session.score} matches`);},1000);}
function selectMatch(button){const s=session;if(s?.id!=='matching'||button.disabled)return;const side=button.dataset.matchSide;s[side]=button;document.querySelectorAll(`[data-match-side="${side}"]`).forEach(tile=>tile.classList.toggle('selected',tile===button));if(!s.left||!s.right)return;const correct=s.left.dataset.matchId===s.right.dataset.matchId;if(correct){const id=s.left.dataset.matchId;s.matched.add(id);s.score++;[s.left,s.right].forEach(tile=>{tile.disabled=true;tile.classList.add('matched');});$('#arcadeMatchStatus').textContent=`Correct — ${s.score}/${s.pairs.length} matched`;s.left=s.right=null;if(s.score===s.pairs.length){const elapsed=Math.max(1,60-s.time);finishView('matching','Crystal Match cleared!',`All ${s.pairs.length} pairs connected with ${s.time} seconds left.`,elapsed);}}else{const left=s.left,right=s.right;$('#arcadeMatchStatus').textContent='Try again — those words do not match.';[left,right].forEach(tile=>tile.classList.add('wrong'));s.left=s.right=null;setTimeout(()=>[left,right].forEach(tile=>tile.classList.remove('selected','wrong')),350);}}
function startShooter(){const lesson=vocabularyPairs(20),pairs=lesson.pairs;session={id:'shooter',source:lesson.source,pairs,index:0,score:0,time:45,ship:50,targets:[],last:performance.now(),running:true,keys:new Set(),waveResolved:false};$('#arcadeContent').innerHTML=`<section class="arcade-game-head arcade-shooter-head"><div><span>TIMED ALIGNMENT GAME</span><h3 id="arcadeShooterPrompt" data-lm-no-interface-translate>Loading word…</h3><p>Move the arrow beneath the matching meaning before the words reach the target line.</p></div><strong><b id="arcadeShooterScore">0</b> · <span id="arcadeShooterTimer">45s</span></strong></section>${lessonSourceMarkup(lesson.source,{selectable:true})}<div class="arcade-shooter-field" id="arcadeShooterField" tabindex="0" aria-label="Star Word Defender alignment field"><div class="arcade-starfield"></div><div class="arcade-alignment-line"><span>ALIGN HERE</span></div><div class="arcade-ship" id="arcadeShip">▲</div><div class="arcade-shooter-controls arcade-alignment-controls"><button type="button" data-ship-move="-1" aria-label="Move arrow left">◀</button><button type="button" data-ship-move="1" aria-label="Move arrow right">▶</button></div></div>`;bindGameLessonSelector('shooter');nextShooterWave();const field=$('#arcadeShooterField');field.focus();field.onkeydown=event=>{if(['ArrowLeft','ArrowRight'].includes(event.key))event.preventDefault();session?.keys.add(event.key);};field.onkeyup=event=>session?.keys.delete(event.key);document.querySelectorAll('[data-ship-move]').forEach(button=>button.onclick=()=>moveShip(Number(button.dataset.shipMove)*12));timer=setInterval(()=>{if(session?.id!=='shooter')return;session.time--;$('#arcadeShooterTimer').textContent=`${session.time}s`;if(session.time<=0)finishShooter();},1000);animation=requestAnimationFrame(shooterFrame);}
function nextShooterWave(){const s=session;if(s?.id!=='shooter')return;const pair=s.pairs[s.index%s.pairs.length],wrong=shuffle(s.pairs.filter(item=>item.id!==pair.id)).slice(0,3),positions=[14,38,62,86];s.current=pair;s.waveResolved=false;s.targets=shuffle([pair,...wrong]).map((item,index)=>({id:item.id,text:item.meaning,x:positions[index],y:-10-Math.random()*10,speed:.034,el:null}));s.index++;$('#arcadeShooterPrompt').textContent=`Align with: ${pair.learn}`;const field=$('#arcadeShooterField');field.querySelectorAll('.arcade-target').forEach(el=>el.remove());s.targets.forEach(target=>{const el=document.createElement('div');el.className='arcade-target';el.setAttribute('data-lm-no-interface-translate','');el.textContent=target.text;el.style.left=`${target.x}%`;target.el=el;field.appendChild(el);});}
function moveShip(delta){if(session?.id!=='shooter')return;session.ship=Math.max(6,Math.min(94,session.ship+delta));$('#arcadeShip').style.left=`${session.ship}%`;}
function resolveShooterAlignment(){const s=session;if(s?.id!=='shooter'||s.waveResolved)return;s.waveResolved=true;const aligned=s.targets.reduce((best,target)=>Math.abs(target.x-s.ship)<Math.abs(best.x-s.ship)?target:best,s.targets[0]),correct=aligned?.id===s.current.id;if(correct)s.score+=1;$('#arcadeShooterScore').textContent=s.score;aligned?.el?.classList.add(correct?'aligned-correct':'aligned-wrong');s.targets.forEach(target=>{if(target!==aligned)target.el?.classList.add('not-aligned');});setTimeout(()=>{if(session!==s||s.id!=='shooter'||!s.running)return;s.targets.forEach(target=>target.el?.remove());s.targets=[];nextShooterWave();},280);}
function shooterFrame(now){const s=session;if(s?.id!=='shooter'||!s.running)return;const delta=Math.min(40,now-s.last);s.last=now;if(s.keys.has('ArrowLeft'))moveShip(-delta*.07);if(s.keys.has('ArrowRight'))moveShip(delta*.07);for(const target of s.targets){target.y+=target.speed*delta;target.el.style.top=`${target.y}%`;}if(!s.waveResolved&&s.targets.some(target=>target.y>=68))resolveShooterAlignment();animation=requestAnimationFrame(shooterFrame);}
function finishShooter(){if(session?.id!=='shooter')return;session.running=false;const score=session.score;finishView('shooter','Defense shift complete!',`You defended the mine for 45 seconds and scored ${score} points.`,score);}
function closeOtherOverlays(){document.getElementById('closeShopBtn')?.click();document.getElementById('utilityClose')?.click();window.syncJapaneseMinerPageScroll?.();}
window.LanguageMinerArcade=Object.freeze({games:()=>GAMES.map(game=>({...game,owned:owned(game.id)})),owned,claim,shopMarkup,bagMarkup,bind,open,close,currentLesson:()=>{const source=currentLesson();return {...source,pairs:source.pairs.map(pair=>({...pair}))};},lessonOptions:()=>lessonOptions().map(option=>({...option})),selectLesson});
window.addEventListener('jm-supporter-entitlement-changed',()=>{if($('#arcadeOverlay')?.classList.contains('open')&&tier()<3)close();});
})();
