// Language Miner Tier 3 Arcade — entitlement-gated study mini games.
(()=>{
'use strict';
const GAMES=[
 {id:'memory',icon:'🧠',name:'Memory Mine',tag:'Memorization game',description:'Reveal cards and remember six learning-language word pairs.',instruction:'Match every learning-language word with its known-language meaning.'},
 {id:'matching',icon:'🔗',name:'Crystal Match',tag:'Matching game',description:'Connect words to their meanings before the clock runs out.',instruction:'Select a learning word, then select its matching meaning.'},
 {id:'shooter',icon:'🚀',name:'Star Word Defender',tag:'Timed shooting game',description:'A Galaga-inspired study challenge with falling answer targets.',instruction:'Move the ship, then shoot the target that matches the prompt.'}
];
const PAIRS_FALLBACK=[['人','person'],['日','day / sun'],['月','moon / month'],['火','fire'],['水','water'],['木','tree'],['山','mountain'],['川','river'],['口','mouth'],['目','eye'],['手','hand'],['友達','friend']];
const $=selector=>document.querySelector(selector),escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const shuffle=values=>{const copy=[...values];for(let index=copy.length-1;index>0;index--){const swap=Math.floor(Math.random()*(index+1));[copy[index],copy[swap]]=[copy[swap],copy[index]];}return copy;};
const tier=()=>Math.max(0,Number(window.japaneseMinerSupporterTier?.()||0));
function ensure(){state.v6=state.v6&&typeof state.v6==='object'?state.v6:{};state.v6.arcadeOwned=Array.isArray(state.v6.arcadeOwned)?[...new Set(state.v6.arcadeOwned.map(String).filter(id=>GAMES.some(game=>game.id===id)))]:[];state.v6.arcadeBest=state.v6.arcadeBest&&typeof state.v6.arcadeBest==='object'&&!Array.isArray(state.v6.arcadeBest)?state.v6.arcadeBest:{};}
function owned(id){ensure();return state.v6.arcadeOwned.includes(String(id));}
function claim(id){ensure();if(tier()<3)return false;if(!GAMES.some(game=>game.id===id))return false;if(!owned(id)){state.v6.arcadeOwned.push(id);save();}return true;}
function gate(feature='Arcade mini games'){return window.japaneseMinerSupporterGate?.(3,feature)||'<p>Patreon Tier 3 is required.</p>';}
function shopMarkup(){ensure();if(tier()<3)return gate('Arcade mini games');return `<section class="arcade-collection-head"><span>PATREON TIER 3 · $5 PATREON COLLECTION</span><h3>🕹️ Study Arcade</h3><p>Claim each mini game once, then launch it anytime from the Shop or your Bag. No Nuggets are charged.</p></section><div class="arcade-library">${GAMES.map(game=>gameCard(game,'shop')).join('')}</div>`;}
function bagMarkup(){ensure();if(tier()<3)return `<section class="arcade-bag-gate"><h3>🕹️ Study Arcade</h3><p>Your Tier 3 mini games will appear here after you connect the $5 Patreon membership.</p>${gate('Arcade mini games')}</section>`;const claimed=GAMES.filter(game=>owned(game.id));return `<div class="owned-inventory-title"><span>Tier 3 game bag · $5 Patreon</span><h3>🕹️ Study Arcade</h3><p>${claimed.length?`${claimed.length} mini game${claimed.length===1?'':'s'} ready to play.`:'Claim mini games from the Shop, then they will appear here.'}</p></div><div class="arcade-library arcade-bag-library">${(claimed.length?claimed:GAMES).map(game=>gameCard(game,claimed.length?'bag':'unclaimed')).join('')}</div>`;}
function gameCard(game,location){const has=owned(game.id),best=state.v6.arcadeBest[game.id],disabled=location==='unclaimed';return `<article class="arcade-game-card ${has?'owned':'claimable'} ${disabled?'unclaimed':''}"><div class="arcade-game-icon">${game.icon}</div><span>${escape(game.tag)}</span><h3>${escape(game.name)}</h3><p>${escape(game.description)}</p><small>${best?`Best: ${escape(bestLabel(game.id,best))}`:has?'Unlocked in your Bag':'Included with Tier 3 · $5 Patreon'}</small><button type="button" data-arcade-${has?'play':'claim'}="${game.id}" ${disabled?'disabled':''}>${has?'Play now':'Unlock mini game'}</button></article>`;}
function bind(container,refresh){container?.querySelectorAll('[data-arcade-claim]').forEach(button=>button.addEventListener('click',()=>{if(claim(button.dataset.arcadeClaim)){setMessage?.('Mini game unlocked and added to your Bag.','correct');refresh?.();}}));container?.querySelectorAll('[data-arcade-play]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.arcadePlay)));}
function vocabularyPairs(count=12){const settings=window.LanguageMinerCourseCloud?.exportCurrent?.()||{},known=String(settings.known||'en'),learning=String(settings.learning||'ja'),source=window.LANGUAGE_MINER_MULTILINGUAL_COURSE_DATA?.vocabulary||[],pairs=[];for(const item of source){const learn=item?.forms?.[learning],meaning=item?.forms?.[known];if(learn&&meaning&&learn!==meaning&&!pairs.some(pair=>pair.learn===learn))pairs.push({id:String(item.id),learn:String(learn),meaning:String(meaning)});if(pairs.length>=80)break;}if(!pairs.length)PAIRS_FALLBACK.forEach(([learn,meaning],index)=>pairs.push({id:`fallback-${index}`,learn,meaning}));return shuffle(pairs).slice(0,count);}
let session=null,timer=null,animation=null;
function shell(){if($('#arcadeOverlay'))return;document.body.insertAdjacentHTML('beforeend',`<div id="arcadeOverlay" class="arcade-overlay" aria-hidden="true"><section class="arcade-panel" role="dialog" aria-modal="true" aria-labelledby="arcadeTitle"><header><button id="arcadeBack" type="button">← Arcade</button><div><span>Tier 3 Study Arcade</span><h2 id="arcadeTitle">Mini game</h2></div><button id="arcadeClose" type="button" aria-label="Close mini game">×</button></header><main id="arcadeContent"></main></section></div>`);$('#arcadeClose').onclick=close;$('#arcadeBack').onclick=renderLibrary;$('#arcadeOverlay').onclick=event=>{if(event.target.id==='arcadeOverlay')close();};}
function open(id=''){ensure();if(tier()<3){window.openJapaneseMinerPatreon?.();return false;}if(id&&!owned(id)){window.openJapaneseMinerArcadeShop?.();return false;}closeOtherOverlays();shell();$('#arcadeOverlay').classList.add('open');$('#arcadeOverlay').setAttribute('aria-hidden','false');window.syncJapaneseMinerPageScroll?.();if(id)start(id);else renderLibrary();return true;}
function close(){stopRuntime();$('#arcadeOverlay')?.classList.remove('open');$('#arcadeOverlay')?.setAttribute('aria-hidden','true');window.syncJapaneseMinerPageScroll?.();}
function stopRuntime(){if(timer){clearInterval(timer);timer=null;}if(animation){cancelAnimationFrame(animation);animation=null;}session=null;}
function renderLibrary(){stopRuntime();$('#arcadeTitle').textContent='Study Arcade';$('#arcadeBack').hidden=true;const content=$('#arcadeContent');content.innerHTML=`<section class="arcade-collection-head"><span>YOUR TIER 3 MINI GAMES</span><h3>Choose a game</h3><p>Each activity uses words from the selected learning language and meanings from the selected known language.</p></section><div class="arcade-library">${GAMES.filter(game=>owned(game.id)).map(game=>gameCard(game,'bag')).join('')||'<p class="arcade-empty">Unlock a mini game from the Shop first.</p>'}</div>`;bind(content,renderLibrary);}
function start(id){if(tier()<3||!owned(id)){close();return false;}stopRuntime();const game=GAMES.find(item=>item.id===id);if(!game)return false;$('#arcadeTitle').textContent=game.name;$('#arcadeBack').hidden=false;if(id==='memory')startMemory();else if(id==='matching')startMatching();else startShooter();return true;}
function record(id,value){ensure();value=Number(value);if(!Number.isFinite(value))return;const old=Number(state.v6.arcadeBest[id]),hasOld=Number.isFinite(old);if(id==='memory'||id==='matching'){if(!hasOld||value<old)state.v6.arcadeBest[id]=value;}else if(!hasOld||value>old)state.v6.arcadeBest[id]=value;save();}
function bestLabel(id,value){return id==='memory'?`${value} moves`:id==='matching'?`${value}s`:`${value} points`;}
function finishView(id,title,detail,value,resultLabel=''){if(Number.isFinite(Number(value)))record(id,value);stopRuntime();const game=GAMES.find(item=>item.id===id),label=resultLabel||(Number.isFinite(Number(value))?bestLabel(id,value):'');$('#arcadeContent').innerHTML=`<section class="arcade-results"><span>${game.icon}</span><h3>${escape(title)}</h3><p>${escape(detail)}</p>${label?`<strong>${escape(label)}</strong>`:''}<div><button type="button" data-arcade-replay="${id}">Play again</button><button type="button" id="arcadeResultsLibrary">Choose another game</button></div></section>`;$('[data-arcade-replay]').onclick=()=>start(id);$('#arcadeResultsLibrary').onclick=renderLibrary;}
function startMemory(){const pairs=vocabularyPairs(6),cards=shuffle(pairs.flatMap(pair=>[{key:pair.id,type:'learn',text:pair.learn},{key:pair.id,type:'meaning',text:pair.meaning}]));session={id:'memory',cards,open:[],matched:new Set(),moves:0,locked:false};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>MEMORIZATION GAME</span><h3>Match all six word pairs</h3><p>Flip two cards. Match each learning word with its known-language meaning.</p></div><strong id="arcadeMemoryMoves">0 moves</strong></section><div class="arcade-memory-grid" data-lm-no-interface-translate>${cards.map((card,index)=>`<button type="button" data-memory-card="${index}" data-memory-key="${escape(card.key)}" aria-label="Hidden memory card"><span>⛏️</span><b>${escape(card.text)}</b></button>`).join('')}</div>`;document.querySelectorAll('[data-memory-card]').forEach(button=>button.onclick=()=>flipMemory(Number(button.dataset.memoryCard)));}
function flipMemory(index){const s=session;if(s?.id!=='memory'||s.locked||s.matched.has(s.cards[index].key)||s.open.includes(index))return;const button=$(`[data-memory-card="${index}"]`);button.classList.add('revealed');button.setAttribute('aria-label',s.cards[index].text);s.open.push(index);if(s.open.length<2)return;s.moves++;$('#arcadeMemoryMoves').textContent=`${s.moves} moves`;const [a,b]=s.open;if(s.cards[a].key===s.cards[b].key&&s.cards[a].type!==s.cards[b].type){s.matched.add(s.cards[a].key);[a,b].forEach(value=>$(`[data-memory-card="${value}"]`).classList.add('matched'));s.open=[];if(s.matched.size===6)setTimeout(()=>finishView('memory','Memory Mine cleared!',`You matched all 6 word pairs in ${s.moves} moves.`,s.moves),350);return;}s.locked=true;setTimeout(()=>{[a,b].forEach(value=>$(`[data-memory-card="${value}"]`)?.classList.remove('revealed'));s.open=[];s.locked=false;},700);}
function startMatching(){const pairs=vocabularyPairs(8);session={id:'matching',pairs,left:null,right:null,matched:new Set(),score:0,time:60};$('#arcadeContent').innerHTML=`<section class="arcade-game-head"><div><span>MATCHING GAME</span><h3>Connect the word pairs</h3><p>Choose one tile from each column. You have 60 seconds.</p></div><strong id="arcadeMatchTimer">60s</strong></section><div class="arcade-match-status" id="arcadeMatchStatus">Select a learning word.</div><div class="arcade-match-board" data-lm-no-interface-translate><div>${shuffle(pairs).map(pair=>`<button type="button" data-match-side="left" data-match-id="${pair.id}">${escape(pair.learn)}</button>`).join('')}</div><div>${shuffle(pairs).map(pair=>`<button type="button" data-match-side="right" data-match-id="${pair.id}">${escape(pair.meaning)}</button>`).join('')}</div></div>`;document.querySelectorAll('[data-match-side]').forEach(button=>button.onclick=()=>selectMatch(button));timer=setInterval(()=>{if(session?.id!=='matching')return;session.time--;$('#arcadeMatchTimer').textContent=`${session.time}s`;if(session.time<=0)finishView('matching','Time is up!',`You connected ${session.score} of ${session.pairs.length} pairs.`,null,`${session.score} matches`);},1000);}
function selectMatch(button){const s=session;if(s?.id!=='matching'||button.disabled)return;const side=button.dataset.matchSide;s[side]=button;document.querySelectorAll(`[data-match-side="${side}"]`).forEach(tile=>tile.classList.toggle('selected',tile===button));if(!s.left||!s.right)return;const correct=s.left.dataset.matchId===s.right.dataset.matchId;if(correct){const id=s.left.dataset.matchId;s.matched.add(id);s.score++;[s.left,s.right].forEach(tile=>{tile.disabled=true;tile.classList.add('matched');});$('#arcadeMatchStatus').textContent=`Correct — ${s.score}/${s.pairs.length} matched`;s.left=s.right=null;if(s.score===s.pairs.length){const elapsed=Math.max(1,60-s.time);finishView('matching','Crystal Match cleared!',`All ${s.pairs.length} pairs connected with ${s.time} seconds left.`,elapsed);}}else{const left=s.left,right=s.right;$('#arcadeMatchStatus').textContent='Try again — those words do not match.';[left,right].forEach(tile=>tile.classList.add('wrong'));s.left=s.right=null;setTimeout(()=>[left,right].forEach(tile=>tile.classList.remove('selected','wrong')),350);}}
function startShooter(){const pairs=vocabularyPairs(20);session={id:'shooter',pairs,index:0,score:0,time:45,ship:50,targets:[],shots:[],last:performance.now(),spawnAt:0,running:true,keys:new Set()};$('#arcadeContent').innerHTML=`<section class="arcade-game-head arcade-shooter-head"><div><span>TIMED SHOOTING GAME</span><h3 id="arcadeShooterPrompt" data-lm-no-interface-translate>Loading word…</h3><p>Shoot the matching meaning. Wrong targets cost 50 points.</p></div><strong><b id="arcadeShooterScore">0</b> · <span id="arcadeShooterTimer">45s</span></strong></section><div class="arcade-shooter-field" id="arcadeShooterField" tabindex="0" aria-label="Star Word Defender game field"><div class="arcade-starfield"></div><div class="arcade-ship" id="arcadeShip">▲</div><div class="arcade-shooter-controls"><button type="button" data-ship-move="-1">◀</button><button type="button" id="arcadeShoot">FIRE</button><button type="button" data-ship-move="1">▶</button></div></div>`;nextShooterWave();const field=$('#arcadeShooterField');field.focus();field.onkeydown=event=>{if(['ArrowLeft','ArrowRight',' '].includes(event.key))event.preventDefault();if(event.key===' ')shoot();else session?.keys.add(event.key);};field.onkeyup=event=>session?.keys.delete(event.key);document.querySelectorAll('[data-ship-move]').forEach(button=>button.onclick=()=>moveShip(Number(button.dataset.shipMove)*12));$('#arcadeShoot').onclick=shoot;timer=setInterval(()=>{if(session?.id!=='shooter')return;session.time--;$('#arcadeShooterTimer').textContent=`${session.time}s`;if(session.time<=0)finishShooter();},1000);animation=requestAnimationFrame(shooterFrame);}
function nextShooterWave(){const s=session;if(s?.id!=='shooter')return;const pair=s.pairs[s.index%s.pairs.length],wrong=shuffle(s.pairs.filter(item=>item.id!==pair.id)).slice(0,3);s.current=pair;s.targets=shuffle([pair,...wrong]).map((item,index)=>({id:item.id,text:item.meaning,x:8+index*24,y:-8-Math.random()*16,speed:.028+Math.random()*.012,el:null}));s.index++;$('#arcadeShooterPrompt').textContent=`Shoot: ${pair.learn}`;const field=$('#arcadeShooterField');field.querySelectorAll('.arcade-target').forEach(el=>el.remove());s.targets.forEach(target=>{const el=document.createElement('button');el.type='button';el.className='arcade-target';el.setAttribute('data-lm-no-interface-translate','');el.textContent=target.text;el.style.left=`${target.x}%`;el.onclick=()=>hitShooterTarget(target);target.el=el;field.appendChild(el);});}
function moveShip(delta){if(session?.id!=='shooter')return;session.ship=Math.max(6,Math.min(94,session.ship+delta));$('#arcadeShip').style.left=`${session.ship}%`;}
function shoot(){const s=session;if(s?.id!=='shooter'||!s.running)return;s.shots.push({x:s.ship,y:78});const el=document.createElement('i');el.className='arcade-laser';el.style.left=`${s.ship}%`;el.style.top='78%';$('#arcadeShooterField').appendChild(el);s.shots[s.shots.length-1].el=el;}
function hitShooterTarget(target){const s=session;if(s?.id!=='shooter'||!s.running)return;const correct=target.id===s.current.id;s.score=Math.max(0,s.score+(correct?100:-50));$('#arcadeShooterScore').textContent=s.score;if(correct){s.targets.forEach(item=>item.el?.remove());s.targets=[];nextShooterWave();}else{target.el?.classList.add('wrong');setTimeout(()=>target.el?.classList.remove('wrong'),200);}}
function shooterFrame(now){const s=session;if(s?.id!=='shooter'||!s.running)return;const delta=Math.min(40,now-s.last);s.last=now;if(s.keys.has('ArrowLeft'))moveShip(-delta*.07);if(s.keys.has('ArrowRight'))moveShip(delta*.07);for(const target of s.targets){target.y+=target.speed*delta;target.el.style.top=`${target.y}%`;}for(const shot of [...s.shots]){shot.y-=.12*delta;shot.el.style.top=`${shot.y}%`;const hit=s.targets.find(target=>Math.abs(target.x-shot.x)<10&&Math.abs(target.y-shot.y)<7);if(hit){shot.el.remove();s.shots.splice(s.shots.indexOf(shot),1);hitShooterTarget(hit);}else if(shot.y<0){shot.el.remove();s.shots.splice(s.shots.indexOf(shot),1);}}if(s.targets.some(target=>target.y>72)){s.score=Math.max(0,s.score-25);$('#arcadeShooterScore').textContent=s.score;s.targets.forEach(target=>target.el.remove());s.targets=[];nextShooterWave();}animation=requestAnimationFrame(shooterFrame);}
function finishShooter(){if(session?.id!=='shooter')return;session.running=false;const score=session.score;finishView('shooter','Defense shift complete!',`You defended the mine for 45 seconds and scored ${score} points.`,score);}
function closeOtherOverlays(){document.getElementById('closeShopBtn')?.click();document.getElementById('utilityClose')?.click();window.syncJapaneseMinerPageScroll?.();}
window.LanguageMinerArcade=Object.freeze({games:()=>GAMES.map(game=>({...game,owned:owned(game.id)})),owned,claim,shopMarkup,bagMarkup,bind,open,close});
window.addEventListener('jm-supporter-entitlement-changed',()=>{if($('#arcadeOverlay')?.classList.contains('open')&&tier()<3)close();});
})();
