// Japanese Miner v6.4.88 - Supabase account and Patreon entitlement client.
(()=>{
"use strict";
const CONFIG=window.JAPANESE_MINER_PATREON_CONFIG||{};
const SESSION_PREFIX="jm_patreon_session_v1:";
const CACHE_PREFIX="jm_patreon_entitlement_v1:";
const TIER_NAMES=["No active tier","Supporter","Companion Keeper","Settlement Founder"];
const linkState={session:null,entitlement:null,busy:false,message:"",messageType:"",callbackHandled:false};
function esc(value){return String(value??"").replace(/[&<>\"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));}
function activeProfile(){return window.japaneseMinerActiveProfile?.()||null;}
function storageSuffix(){return activeProfile()?.id||"guest";}
function sessionKey(){return SESSION_PREFIX+storageSuffix();}
function cacheKey(){return CACHE_PREFIX+storageSuffix();}
function integrationEnabled(){return CONFIG.enabled===true&&/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(String(CONFIG.supabaseUrl||""))&&String(CONFIG.supabaseAnonKey||"").length>30&&!String(CONFIG.supabaseAnonKey).includes("YOUR_");}
function functionsUrl(name){return `${String(CONFIG.supabaseUrl).replace(/\/$/,"")}/functions/v1/${name}`;}
function authUrl(path){return `${String(CONFIG.supabaseUrl).replace(/\/$/,"")}/auth/v1/${path}`;}
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||"null");}catch{return null;}}
function writeJson(key,value){try{if(value==null)localStorage.removeItem(key);else localStorage.setItem(key,JSON.stringify(value));}catch{}}
function normalizeSession(payload){if(!payload?.access_token)return null;return {accessToken:payload.access_token,refreshToken:payload.refresh_token||"",expiresAt:Number(payload.expires_at)||Math.floor(Date.now()/1000)+Number(payload.expires_in||3600),user:payload.user||null};}
function loadProfileConnection(){linkState.session=readJson(sessionKey());linkState.entitlement=readJson(cacheKey());applyCachedEntitlement();}
function saveSession(session){linkState.session=session;writeJson(sessionKey(),session);}
function setNotice(message,type=""){linkState.message=message;linkState.messageType=type;renderLinkPanel();}
function applyEntitlement(entitlement,source="server"){const tier=Math.max(0,Math.min(3,Number(entitlement?.tier)||0));linkState.entitlement=Object.assign({},entitlement,{tier,source});window.setJapaneseMinerVerifiedSupporterEntitlement?.(linkState.entitlement);}
function clearEntitlement(){writeJson(cacheKey(),null);applyEntitlement({tier:0,connected:false,verified_at:null,grace_until:null},"none");}
function applyCachedEntitlement(){const cached=linkState.entitlement,graceUntil=Date.parse(cached?.grace_until||"");if(cached&&Number(cached.tier)>0&&Number.isFinite(graceUntil)&&graceUntil>Date.now())applyEntitlement(cached,"offline-cache");else applyEntitlement({tier:0,connected:!!cached?.connected},"unverified");}
async function jsonRequest(url,{method="GET",body=null,token=null}={}){const headers={apikey:String(CONFIG.supabaseAnonKey||""),Accept:"application/json"};if(body!=null)headers["Content-Type"]="application/json";if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(url,{method,headers,body:body==null?undefined:JSON.stringify(body)});let payload={};try{payload=await response.json();}catch{}if(!response.ok)throw new Error(payload?.error_description||payload?.msg||payload?.error||payload?.message||`Request failed (${response.status})`);return payload;}
async function refreshSession(){const current=linkState.session;if(!current?.refreshToken)throw new Error("Your cloud session expired. Please sign in again.");const payload=await jsonRequest(authUrl("token?grant_type=refresh_token"),{method:"POST",body:{refresh_token:current.refreshToken}}),session=normalizeSession(payload);if(!session)throw new Error("Supabase did not return a refreshed session.");saveSession(session);return session;}
async function validSession(){if(!linkState.session)return null;if(Number(linkState.session.expiresAt||0)>Math.floor(Date.now()/1000)+60)return linkState.session;try{return await refreshSession();}catch(error){saveSession(null);throw error;}}
async function functionRequest(name,{method="GET",body=null}={}){const session=await validSession();if(!session)throw new Error("Sign in to your supporter account first.");return jsonRequest(functionsUrl(name),{method,body,token:session.accessToken});}
async function signUp(email,password){const profile=activeProfile(),payload=await jsonRequest(authUrl("signup"),{method:"POST",body:{email,password,data:{game_profile_id:profile?.id||"",game_profile_name:profile?.name||""}}}),session=normalizeSession(payload);if(session){saveSession(session);await refreshEntitlement({silent:true});setNotice("Cloud supporter account created.","success");}else setNotice("Account created. Check your email to confirm it, then sign in here.","success");}
async function signIn(email,password){const payload=await jsonRequest(authUrl("token?grant_type=password"),{method:"POST",body:{email,password}}),session=normalizeSession(payload);if(!session)throw new Error("Supabase did not return a session.");saveSession(session);await refreshEntitlement({silent:true});setNotice("Signed in to your supporter account.","success");}
async function signOut(){const token=linkState.session?.accessToken;if(token)try{await jsonRequest(authUrl("logout"),{method:"POST",token});}catch{}saveSession(null);clearEntitlement();setNotice("Supporter account signed out on this device.","success");}
async function refreshEntitlement({silent=false}={}){if(!integrationEnabled()){clearEntitlement();renderLinkPanel();return null;}if(!linkState.session){applyCachedEntitlement();renderLinkPanel();return null;}try{const payload=await functionRequest("patreon-status"),entitlement={connected:payload.connected===true,tier:Math.max(0,Math.min(3,Number(payload.tier)||0)),tier_name:payload.tier_name||TIER_NAMES[Number(payload.tier)||0],patron_status:payload.patron_status||null,last_charge_status:payload.last_charge_status||null,verified_at:payload.verified_at||new Date().toISOString(),grace_until:payload.grace_until||null};writeJson(cacheKey(),entitlement);applyEntitlement(entitlement,"server");if(!silent)setNotice(entitlement.connected?`Membership refreshed: ${entitlement.tier_name}.`:"Your Patreon account is not connected yet.",entitlement.tier>0?"success":"");else renderLinkPanel();return entitlement;}catch(error){applyCachedEntitlement();if(!silent)setNotice(`Could not verify Patreon right now. ${error.message}`,"error");else renderLinkPanel();return null;}}
async function connectPatreon(){const payload=await functionRequest("patreon-start",{method:"POST",body:{profile_id:activeProfile()?.id||""}});if(!/^https:\/\/www\.patreon\.com\/oauth2\/authorize(?:\?|$)/.test(String(payload.authorization_url||"")))throw new Error("The backend returned an invalid Patreon authorization address.");location.assign(payload.authorization_url);}
async function unlinkPatreon(){if(!confirm("Disconnect Patreon from this supporter account? Patreon benefits will lock immediately."))return;await functionRequest("patreon-unlink",{method:"POST"});clearEntitlement();setNotice("Patreon disconnected. Your Patreon subscription was not cancelled.","success");}
function accountEmail(){return linkState.session?.user?.email||"Cloud account";}
function noticeMarkup(){return linkState.message?`<div class="patreon-link-notice ${esc(linkState.messageType)}" role="status">${esc(linkState.message)}</div>`:"";}
function connectionMarkup(){
  if(!integrationEnabled())return `<section id="patreonLinkAccount" class="patreon-link-account setup-needed"><span>ADMINISTRATOR SETUP REQUIRED</span><h3>Patreon linking is installed but not configured</h3><p>Deploy the included Supabase migration and functions, then enter the public project URL and anon key in <code>patreon-config.js</code>. Membership secrets stay on the backend.</p><a class="supporter-join-link" href="${esc(CONFIG.patreonJoinUrl||"https://www.patreon.com/")}" target="_blank" rel="noopener">View Patreon memberships</a></section>`;
  if(!linkState.session)return `<section id="patreonLinkAccount" class="patreon-link-account"><span>SECURE SUPPORTER ACCOUNT</span><h3>Connect your game to Patreon</h3><p>Create or sign in to the cloud account that will own your verified Patreon benefits. Your game progress remains in the selected local profile.</p>${noticeMarkup()}<form id="patreonCloudAuthForm"><label>Email<input id="patreonCloudEmail" type="email" autocomplete="email" required></label><label>Password<input id="patreonCloudPassword" type="password" minlength="8" autocomplete="current-password" required></label><div class="patreon-link-actions"><button class="primary" name="action" value="signin" type="submit">Sign in</button><button name="action" value="signup" type="submit">Create account</button></div></form><small>Passwords and Patreon credentials are handled by the configured Supabase project, not stored in the game save.</small></section>`;
  const ent=linkState.entitlement||{},tier=Math.max(0,Math.min(3,Number(ent.tier)||0)),connected=ent.connected===true,verified=ent.verified_at?new Date(ent.verified_at).toLocaleString():"Not verified yet";
  return `<section id="patreonLinkAccount" class="patreon-link-account ${tier>0?"active-member":""}"><span>${tier>0?`ACTIVE PATREON TIER ${tier}`:"SUPPORTER ACCOUNT"}</span><h3>${tier>0?esc(ent.tier_name||TIER_NAMES[tier]):connected?"Patreon connected — no paid tier active":"Ready to connect Patreon"}</h3><p>Signed in as <strong>${esc(accountEmail())}</strong></p>${tier>0?`<div class="patreon-entitlement-badge"><b>${tier}</b><span>${esc(ent.tier_name||TIER_NAMES[tier])}<small>Verified ${esc(verified)}${ent.source==="offline-cache"?" · offline grace":""}</small></span></div>`:connected?"<p>Your account is linked, but Patreon is not currently reporting an entitled Japanese Miner tier.</p>":"<p>Link the Patreon account used for your Japanese Miner membership. You only need to do this once.</p>"}${noticeMarkup()}<div class="patreon-link-actions">${connected?"":'<button id="connectPatreonBtn" class="primary" type="button">Connect Patreon</button>'}<button id="refreshPatreonBtn" type="button">Refresh membership</button>${connected?'<button id="unlinkPatreonBtn" type="button">Disconnect Patreon</button>':""}<button id="signOutSupporterBtn" type="button">Sign out</button></div></section>`;
}
function renderLinkPanel(){const box=document.getElementById("v6FeedbackContent");if(!box)return;const note=box.querySelector(".supporter-link-note");if(note)note.textContent="Link your Patreon account to unlock the tier reported by your active membership.";box.querySelector("#patreonLinkAccount")?.remove();box.insertAdjacentHTML("afterbegin",connectionMarkup());const form=document.getElementById("patreonCloudAuthForm");if(form)form.onsubmit=event=>{event.preventDefault();const email=document.getElementById("patreonCloudEmail").value.trim(),password=document.getElementById("patreonCloudPassword").value,action=event.submitter?.value||"signin";return runBusy(async()=>{if(password.length<8)throw new Error("Use a password with at least 8 characters.");await (action==="signup"?signUp(email,password):signIn(email,password));});};const connect=document.getElementById("connectPatreonBtn");if(connect)connect.onclick=()=>runBusy(connectPatreon);const refresh=document.getElementById("refreshPatreonBtn");if(refresh)refresh.onclick=()=>runBusy(()=>refreshEntitlement());const unlink=document.getElementById("unlinkPatreonBtn");if(unlink)unlink.onclick=()=>runBusy(unlinkPatreon);const signout=document.getElementById("signOutSupporterBtn");if(signout)signout.onclick=()=>runBusy(signOut);box.querySelectorAll("#patreonLinkAccount button").forEach(button=>button.disabled=linkState.busy);}
async function runBusy(task){if(linkState.busy)return;linkState.busy=true;renderLinkPanel();try{await task();}catch(error){setNotice(error.message||"The Patreon connection could not be completed.","error");}finally{linkState.busy=false;renderLinkPanel();}}
function handleOAuthReturn(){if(linkState.callbackHandled)return;const url=new URL(location.href),result=url.searchParams.get("patreon");if(!result)return;linkState.callbackHandled=true;const detail=url.searchParams.get("detail")||"";url.searchParams.delete("patreon");url.searchParams.delete("detail");history.replaceState({},"",url.pathname+(url.search?url.search:"")+url.hash);if(result==="linked"){linkState.message="Patreon connected successfully. Verifying your membership…";linkState.messageType="success";refreshEntitlement({silent:true}).finally(()=>window.openJapaneseMinerPatreon?.());}else{linkState.message=detail||"Patreon did not complete the connection.";linkState.messageType="error";window.openJapaneseMinerPatreon?.();}}
function profileLoaded(){loadProfileConnection();refreshEntitlement({silent:true});handleOAuthReturn();}
window.renderJapaneseMinerPatreonLinking=renderLinkPanel;
window.refreshJapaneseMinerPatreonEntitlement=refreshEntitlement;
window.addEventListener("jm-profile-loaded",profileLoaded);
window.addEventListener("jm-profile-logged-out",()=>{linkState.session=null;linkState.entitlement=null;applyEntitlement({tier:0,connected:false},"none");});
if(activeProfile())profileLoaded();else handleOAuthReturn();
})();
