const CACHE_NAME='language-miner-v6.4.144-community-shortcuts-r1';
const APP_SHELL=[
  './',
  './index.html',
  './styles.css',
  './v5.css',
  './v6-6460.css',
  './multilingual-preview.css',
  './parent-teacher-center.css',
  './writing-practice.css',
  './companion-wardrobe.css',
  './avatar-holiday-specials.css',
  './settlement-village.css',
  './legal-compliance.css',
  './legal-policy.css',
  './privacy.html',
  './terms.html',
  './n5-vocabulary-1000.js',
  './multilingual-course-data.js',
  './additional-language-packs.js',
  './mine-cosmetic-localization.js',
  './full-interface-localization.js',
  './patreon-copy-localization.js',
  './parent-teacher-localization.js',
  './generated-interface-localization.js',
  './game-6460.js',
  './v5-6400.js',
  './qr-code.js',
  './v6.js',
  './arcade-games.js',
  './recovery-6460.js',
  './patreon-config.js',
  './cloud-auth.js',
  './auth-utilities.js',
  './legal-compliance.js',
  './patreon-linking.js',
  './interface-localization.js',
  './multilingual-preview.js',
  './parent-teacher-center.js',
  './game-guide.js',
  './writing-practice.js',
  './manifest.webmanifest',
  './anime-miner-v1.png',
  './avatar-holiday-lantern-yukata-layer-v1.png',
  './avatar-holiday-cozy-christmas-layer-v1.png',
  './avatar-holiday-santa-celebration-layer-v1.png',
  './avatar-holiday-summer-matsuri-layer-v1.png',
  './settlement-village-map-v1.png',
  './language-miner-logo.png',
  './patreon-tier-1-supporter.png',
  './patreon-tier-2-companion-keeper.png',
  './patreon-tier-3-settlement-founder.png',
  './companion-3d-squirrel.png',
  './companion-3d-cat.png',
  './companion-3d-mole.png',
  './companion-3d-panda.png',
  './companion-3d-kitsune.png',
  './companion-3d-tanuki.png',
  './companion-3d-tiger.png',
  './companion-3d-lion.png',
  './companion-3d-crystal.png',
  './companion-3d-golem.png',
  './companion-3d-dragon.png',
  './companion-3d-academy-squirrel.png',
  './companion-3d-academy-cat.png',
  './companion-3d-academy-mole.png',
  './companion-3d-academy-panda.png',
  './companion-3d-academy-kitsune.png',
  './companion-3d-academy-tanuki.png',
  './companion-3d-academy-tiger.png',
  './companion-3d-academy-lion.png',
  './companion-3d-academy-crystal.png',
  './companion-3d-academy-golem.png',
  './companion-3d-academy-dragon.png',
  './companion-3d-festival-squirrel.png',
  './companion-3d-festival-cat.png',
  './companion-3d-festival-mole.png',
  './companion-3d-festival-panda.png',
  './companion-3d-festival-kitsune.png',
  './companion-3d-festival-tanuki.png',
  './companion-3d-festival-tiger.png',
  './companion-3d-festival-lion.png',
  './companion-3d-festival-crystal.png',
  './companion-3d-festival-golem.png',
  './companion-3d-festival-dragon.png',
  './companion-3d-guardian-squirrel.png',
  './companion-3d-guardian-cat.png',
  './companion-3d-guardian-mole.png',
  './companion-3d-guardian-panda.png',
  './companion-3d-guardian-kitsune.png',
  './companion-3d-guardian-tanuki.png',
  './companion-3d-guardian-tiger.png',
  './companion-3d-guardian-lion.png',
  './companion-3d-guardian-crystal.png',
  './companion-3d-guardian-golem.png',
  './companion-3d-guardian-dragon.png',
  './language-miner-icon-32.png',
  './language-miner-icon-180.png',
  './language-miner-icon-192.png',
  './language-miner-icon-512.png',
  './language-miner-icon-maskable-192.png',
  './language-miner-icon-maskable-512.png'
];

self.addEventListener('install',event=>{
  event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(APP_SHELL)).then(()=>self.skipWaiting()));
});

self.addEventListener('activate',event=>{
  event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>(key.startsWith('japanese-miner-')||key.startsWith('language-miner-'))&&key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));
});

self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.method!=='GET'||request.headers.has('range'))return;
  const url=new URL(request.url);
  if(url.origin!==self.location.origin)return;
  if(request.mode==='navigate'){
    event.respondWith(fetch(request).then(response=>{
      const copy=response.clone();
      caches.open(CACHE_NAME).then(cache=>cache.put('./index.html',copy));
      return response;
    }).catch(()=>caches.match('./index.html')));
    return;
  }
  event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{
    if(response&&response.status===200){
      const copy=response.clone();
      caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));
    }
    return response;
  })));
});
